### PR TITLE
fix for no reload under win32

### PR DESCRIPTION
**Pull request by rootnot**
Hi Brandon,
Nice piece. Respect.
It didn't work for me on windows, investigated a little and here it is.

### CODE REVIEW

**Comment by brandonweiss** [comment]
Thanks! And thanks for letting me know about the bug!

Hmm, I think I might know what the issue is. I vaguely remember that most of the glob libraries don’t actually support Windows-style path separators (`\`) in globs. I was using `pathJoin` which would product a glob that looks something like `source\**\*` on Windows, but it actually needs to be `source/**/*`, the same path separator that’s used on macOS/Linux.

Could you try this change and let me know if it works?

```diff
- let sourceGlob = pathJoin(source, "**", "*")
+ let sourceGlob = `${source}/**/*`
```

**Comment by rootnot** [comment]
Checked. Working on win@1809, node@12.4.0.

**Comment by brandonweiss** [comment]
@rootnot Awesome! Would you mind squashing them down into one commit? Thanks!

**Comment by rootnot** [comment]
You got it

**Pull request merged**
